### ISSUE TITLE
第一次请求的时候，无法获取到 storage 中的 session

### ISSUE THREAD

**Issue by uax** [IvinWu/weRequest#11]
如下代码，我想把 storage 中存储的 session 值带入到 header 来做服务端鉴权：
`weRequest.request({
   url: 'order/detail',
    header: {'Authorization':'Bearer ' + wx.getStorageSync('session')},
    data: {
        id: '107B7615E04AE64CFC10'
    },
    success: function (data) {
        // 省略...
    }
})
`
初次登录，weRequest.init会初始化，然后获取到了 session，存到 storage 中，但是在接下来的请求 order/detail 的时候，获取不到 storage 中的 session 值。
或许我的操作步骤不正确，应该怎么让他把 storage 中的 session 值带入到 header 中？

**Comment by IvinWu** [comment]
`weRequest.init()`时，其实还不会去获取session，只有当需要发起请求的时候，组件才会去判断登陆态状态，从而决定是否要去登陆拿session。
你的这种场景，可以考虑在初始化时候显示地调用一下`weRequest.login()`，这样能手动触发一次登陆，之后你就能拿到session了。
当然，我认为更好的方式是，组件自带支持开发者通过配置，把session带在请求的header中，后续版本将会支持，感谢反馈。

**Comment by uax** [comment]
嗯，谢谢您的回答了。
期待后续的开发,你说的方式挺好的，经您提醒，我换了一种方式，目前在直接在源文件中硬编码把 Authorization 写入到了 header 中，移除了 URL 附带的参数。
