### ISSUE TITLE
请问可以支持把session放在header中吗

### ISSUE THREAD

**Issue by solarhell** [IvinWu/weRequest#19]
如题，现在是默认通过 url query string 来传session的。没有找到配置到 header 里的选项。
期望可以配置成
```
header : {
	'Authroization': JWT,
}
```
谢谢

**Comment by solarhell** [comment]
目前看到 https://github.com/IvinWu/weRequest/blob/399b465e9bb327f2e24f5093a5ab25d0b15e35c3/src/module/requestHandler.ts#L69-L74

如果可以的话我可以提一个pr来增加一个配置session如何发送的选项。

**Comment by IvinWu** [comment]
欢迎PR @solarhell

**Comment by solarhell** [comment]
https://github.com/IvinWu/weRequest/blob/399b465e9bb327f2e24f5093a5ab25d0b15e35c3/src/module/requestHandler.ts#L68

你好，我感觉这里会有一些问题，倾向于改成所有请求都带上session，不需要登录态的直接使用wx.request。
因为有些API只接受GET请求，但是需要在header里带上session。

ping @IvinWu

**Comment by solarhell** [comment]
#20

**Comment by SunnyW11** [comment]
`export const request = function(obj, isAutoAddAuthToHeader = true){
  if (isAutoAddAuthToHeader){
    let token = wx.getStorageSync('token')
    if (obj.header) {
      obj.header = Object.assign(obj.header,{
        Authorization: token
      })
    } else {
      obj.header = {
        Authorization: token
      }
    }
  }
  return weRequest.request(obj)
}
`

我基于weRequest自己简单封装了一层，但是在token过期后自动登录后，Authorization就不能自动加进去了 ，因为codeToSession后不会调用我封装的方法，还是会自动加到header，感觉要去改weRequest里面的源码了

**Comment by IvinWu** [comment]
1.2.13 版本已支持

**Comment by tinyRatP** [comment]
> 1.2.13 版本已支持

请问下如何将 session 放在 header 内而不是 query'string 呢？看了下文档和源码，貌似都不行
