### ISSUE TITLE
如果需要获取用户敏感信息如何处理？？

### ISSUE THREAD

**Issue by style-clear** [IvinWu/weRequest#2]
如果需要获取用户敏感信息如何处理？？

**Comment by IvinWu** [comment]
@style-clear 获取用户信息请使用`wx.getUserInfo(OBJECT)`，跟本组件的功能不相关哈

**Comment by lain1936** [comment]
应该还是有必要吧。   腾讯的第三步不会直接返回你openid,  需要getUserInfo再请求相关信息后端解密才能得到关键信息，不然后端不能长久维持用户的状态，  因为同一个用户过期后能申请到不同后台的session，长久维持的话需要可以标识用户唯一的key

**Comment by IvinWu** [comment]
@lain1936 https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxloginobject
code 换取 session_key 的同时，微信服务器会返回当前用户的openid，这个时候业务服务器生成3rd_session，然后需要把openid和3rd_session的对应关系存起来，日后，openid就是你所说的标识用户唯一的key了

**Comment by hexcode007** [comment]
@IvinWu  这个组件挺好用的,谢谢分享!
有这样一种需求, 在用code换取3rd_session时,如果服务端检测到获取的openid 是用户第一次注册,  这时候需要获取用户的敏感信息保存到数据库,  这种情况下该如何处理?
