### ISSUE TITLE
Promise方式不对错误信息进行处理

### ISSUE THREAD

**Issue by mwindson** [IvinWu/weRequest#34]
### 问题
 目前`weRequest`的promise写法设置了`catchErr`时会对错误信息进行处理，开发者无法得到原始的错误信息

### 建议
1. 暂时采用回调的方式使用`weRequest`
2. 修改promise在设置了`catchErr`时的错误信息逻辑  **break change**

**Comment by jasonliao** [comment]
https://github.com/IvinWu/weRequest/pull/51 这个 pr 是不是可以解决这个问题？逻辑错误时会把原始的错误信息一并返回

**Comment by IvinWu** [comment]
> #51 这个 pr 是不是可以解决这个问题？逻辑错误时会把原始的错误信息一并返回

bingo
