### ISSUE TITLE
对于并发请求如何解决？

### ISSUE THREAD

**Issue by ldwonday** [IvinWu/weRequest#36]
一个页面需要一开始同时需要发出三个异步请求，假如登录状态已经过期了，那么这三个请求都会去调用wx.login()去后台登录，然后session会错乱。

**Comment by IvinWu** [comment]
1）在1.x版本中，登录状态已经过期时同时有多个并发情况的情况下，只会发起一个wx.login()，所有业务请求会等待新的登录态返回之后再重新发起。
2）在2.x版本中，由于不存在独立的登录接口了，所以多个业务请求会同时带上js_code发起，的确会出现调用多次wx.login()，但是这里wx.login()返回的js_code是不会覆盖的，也就是说多次调用wx.login()返回的js_code都是可用的（每个只能用一次），因此都能换取到新的登录态。当然，这里会造成生成了3个登录态，且由于时序问题可能返回到小程序端时顺序不一致，因此业务需要做好兼容，保证登录态都可用。
