### ISSUE TITLE
如何获取安装最新版本

### ISSUE THREAD

**Issue by tinyRatP** [IvinWu/weRequest#39]
NPM 官方仓库的 `we-request` 最新版本为 `1.2.11`。

但是我看到 README 已经为 `1.2.13` 了，我该如何获得最新版本呢，除了离线下载之外。

因为我需要自定义 Header，所以需要升级版本。另外，我该如何把 `SessionName` 放入 Header 之中呢？

**Comment by tinyRatP** [comment]
#20 貌似这个 pr 能符合要求。
请问会跟进吗？

**Comment by IvinWu** [comment]
npm已更新
