### ISSUE TITLE
mock模式下complete回调没有处理

### ISSUE THREAD

**Issue by JeffAAA** [IvinWu/weRequest#4]
function mock(obj) {
        var res = {
            data: mockJson[obj.url]
        };
        if (successTrigger(res.data) && typeof obj.success == "function") {
            // 接口返回成功码
            obj.success(successData(res.data));
        } else {
            // 接口返回失败码
            fail(obj, res);
        }
    }

实际使用时，mock模式下的complete回调没有生效。貌似mock模式下没有对complete回调进行处理。

**Comment by IvinWu** [comment]
已修复
