### ISSUE TITLE
因为找不到您的联系方式，只能再issue请教个问题。

### ISSUE THREAD

**Issue by jprothwell** [IvinWu/weRequest#43]
请问weRequest这个webpack库框架是使用了什么地方的脚手架生成的？还是您手动编写的webpack框架，我觉着这个结构非常棒也想以后用这个模版编写，静待您的回答谢谢。

**Comment by IvinWu** [comment]
我这里的webpack只用了很简单的能力，自己写的。更详细的webpack配置可以查看webpack官网哈：https://www.webpackjs.com/concepts/
