### ISSUE TITLE
登陆后，get请求强制把session附在query上，post请求强制把session附在body里不合理

### ISSUE THREAD

**Issue by guanpengchn** [IvinWu/weRequest#50]
登陆后，get请求强制把session附在query上，post请求强制把session附在body里不合理

**Comment by guanpengchn** [comment]
可能我想附在请求头上，这里面的参数附上是我不需要的

**Comment by guanpengchn** [comment]
还有就是在没有登录态的时候访问业务接口，登陆请求发生后，wx.getStorageSync()拿不到值

**Comment by IvinWu** [comment]
1.5.0 / 2.3.0 已支持init方法配置beforeSend，可实现个性化需求。
登陆请求发生后，storage是异步设置的，可以看看是否是时序问题
