### ISSUE TITLE
单次请求怎样跳过登录验证

### ISSUE THREAD

**Issue by jiaicon** [IvinWu/weRequest#53]
如果我只需要获取页面数据，不需要登录，怎样发送请求？

**Comment by IvinWu** [comment]
不需要登录态的请求，可直接使用 `wx.request`

**Comment by jiaicon** [comment]
我觉得可以加个参数进来，没必要还使用两套请求，
![image](https://user-images.githubusercontent.com/34124517/123962139-b4429c80-d9e3-11eb-9325-facdbdda1a5a.png)
应该可以实现的
